# Generated by Django 2.2.3 on 2019-07-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_auto_20190717_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='Year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
