# Generated by Django 2.2 on 2019-05-25 14:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarProfile',
            fields=[
                ('author_name', models.CharField(max_length=100)),
                ('profile_url', models.URLField(primary_key=True, serialize=False)),
                ('publication_title', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
