# Generated by Django 2.2.3 on 2019-07-15 09:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_scholarprofile_normalized_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='citations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='coAuthors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
