# Generated by Django 2.2.3 on 2020-08-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20200807_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarredScholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('work', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
