# Generated by Django 2.2.3 on 2020-08-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_starredscholar'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholardata',
            name='isStarred',
            field=models.BooleanField(default=False),
        ),
    ]
