# Generated by Django 2.2.3 on 2019-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_scholarprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='publications',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
