# Generated by Django 2.2.3 on 2020-08-08 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0004_scholardata_isstarred'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StarredScholar',
        ),
        migrations.AlterField(
            model_name='scholardata',
            name='scholarImage',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='scholardata',
            name='scholarName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='scholardata',
            name='titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), null=True, size=None),
        ),
    ]
