# Generated by Django 2.2.3 on 2019-07-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0006_scholarprofile_tcitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarprofile',
            name='Gindex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='Hindex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scholarprofile',
            name='Mindex',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
