# Generated by Django 2.2.3 on 2019-07-24 04:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0010_auto_20190719_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarprofile',
            name='citations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
