# Generated by Django 2.2.3 on 2019-07-24 04:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0011_auto_20190724_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarprofile',
            name='citations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
